<?php
define('NOMBRE_SERVIDOR', 'localhost');
define('NOMBRE_USUARIO', 'root');
define('PASSWORD', '');
define('NOMBRE_BD', 'elogic');

define('SERVIDOR', 'http://localhost/rfq/');
define('ERROR', SERVIDOR . 'error');
define('PERFIL', SERVIDOR . 'perfil/');
define('LOGOUT', SERVIDOR . 'logout');
define('REGISTRO', PERFIL . 'registro');
define('REGISTRO_CORRECTO', PERFIL . 'registro_correcto');
define('ELIMINAR_USUARIO', PERFIL . 'eliminar_usuario');
define('COTIZACIONES', PERFIL . 'cotizaciones/');
define('GSA_BUY', COTIZACIONES . 'gsa_buy');
define('FEDBID', COTIZACIONES . 'fedbid');
define('EMAILS', COTIZACIONES . 'emails');
define('FINDFRP', COTIZACIONES . 'findfrp');
define('EMBASSIES', COTIZACIONES . 'embassies');
define('FBO', COTIZACIONES . 'fbo');
define('COMPLETADOS', PERFIL . 'completados/');
define('GSA_BUY_COMPLETADOS', COMPLETADOS . 'gsa_buy');
define('FEDBID_COMPLETADOS', COMPLETADOS . 'fedbid');
define('EMAILS_COMPLETADOS', COMPLETADOS . 'emails');
define('FINDFRP_COMPLETADOS', COMPLETADOS . 'findfrp');
define('EMBASSIES_COMPLETADOS', COMPLETADOS . 'embassies');
define('FBO_COMPLETADOS', COMPLETADOS . 'fbo');
define('SUBMITTED', PERFIL . 'submitted/');
define('GSA_BUY_SUBMITTED', SUBMITTED . 'gsa_buy');
define('FEDBID_SUBMITTED', SUBMITTED . 'fedbid');
define('EMAILS_SUBMITTED', SUBMITTED . 'emails');
define('FINDFRP_SUBMITTED', SUBMITTED . 'findfrp');
define('EMBASSIES_SUBMITTED', SUBMITTED . 'embassies');
define('FBO_SUBMITTED', SUBMITTED . 'fbo');
define('AWARD', PERFIL . 'award/');
define('GSA_BUY_AWARD', AWARD . 'gsa_buy');
define('FEDBID_AWARD', AWARD . 'fedbid');
define('EMAILS_AWARD', AWARD . 'emails');
define('FINDFRP_AWARD', AWARD . 'findfrp');
define('EMBASSIES_AWARD', AWARD . 'embassies');
define('FBO_AWARD', AWARD . 'fbo');
define('NUEVA_COTIZACION', COTIZACIONES . 'nuevo');
define('REGISTRO_COTIZACION_CORRECTO', COTIZACIONES . 'registro_cotizacion_correcto');
define('EDITAR_COTIZACION', COTIZACIONES . 'editar_cotizacion');
define('DOCS', SERVIDOR . 'documentos/');
define('PROPOSAL', SERVIDOR . 'proposal');
define('ADD_ITEM', COTIZACIONES . 'add_item');
define('ADD_PROVIDER', COTIZACIONES . 'add_provider');
define('EDIT_ITEM', COTIZACIONES . 'edit_item');
define('EDIT_PROVIDER', COTIZACIONES . 'edit_provider');

define('RUTA_CSS', SERVIDOR . 'css/');
define('RUTA_JS', SERVIDOR . 'js/');
define('RUTA_IMG', SERVIDOR . 'img/');
define('PLUGINS', SERVIDOR . 'plugins/');
define('DIST', SERVIDOR . 'dist/');
?>
